# Site settings
title: My kernel
email: westion717@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kernel.wuzx.me" # the base hostname & protocol for your site
twitter_username: westion717
github_username:  westion717

# Build settings
markdown: kramdown
